CREATE TABLE CompAmbiti(
idProgetto	INTEGER,
idAmbito 	INTEGER,

CONSTRAINT Fk1FOREIGN KEY (idProgetto) REFERENCES progetto (idProgetto) ON UPDATE CASCADE, ON DELETE CASCADE,
CONSTRAINT Fk2 FOREIGN KEY (idAmbito) REFERENCES Ambiti (idAmbito) ON UPDATE CASCADE, ON DELETE CASCADE,

)
