CREATE TABLE Valutazione(
	idValutazione INTEGER PRIMARY KEY,
	Recensione VARCHAR(1000) NOT NULL,
	Stelle INTEGER NOT NULL,
	DataV DATE NOT NULL DEFAULT '1940-01-01',
	
	CONSTRAINT CKStelle CHECK (Stelle BETWEEN 0 AND 5)
);